// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoeExportInvoice.Api.Data;

#nullable disable

namespace ShoeExportInvoice.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912005749_ContractScopeAndAuditGuards")]
    partial class ContractScopeAndAuditGuards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.CustomsSettlementItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ClosingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HsCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InPeriodExport")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("InPeriodProduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("OtherExport")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SettlementPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SettlementPeriodId");

                    b.ToTable("CustomsSettlementItems");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.CustomsSettlementPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContractFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractNo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomsOffice")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractFolderId", "ToDate");

                    b.ToTable("CustomsSettlementPeriods");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.MasterDataFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractNo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultPairsPerCarton")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PoSuffix")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("MasterDataFolders");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.ProductMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HsCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("PairPerCarton")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StyleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPriceCMT")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("UnitPriceCMT_Go")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("UnitPriceDAP")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("UnitPriceDAP_Go")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StyleCode")
                        .IsUnique()
                        .HasFilter("\"FolderId\" IS NULL");

                    b.HasIndex("FolderId", "StyleCode")
                        .IsUnique();

                    b.ToTable("ProductMasters");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.ShipmentOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClearanceDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContractFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractNo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomsAttachmentFileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomsAttachmentFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomsChannel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomsDeclarationType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CustomsGrossWeight")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("CustomsOffice")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomsPackageQty")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CustomsTotalCmt")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("CustomsTotalDap")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("DeclarationNo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryTerms")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PoSuffix")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationNo");

                    b.HasIndex("InvoiceNo")
                        .IsUnique();

                    b.HasIndex("ContractFolderId", "Status", "CustomsDeclarationType", "ClearanceDate");

                    b.ToTable("ShipmentOrders");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.ShipmentOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullItemCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PairPerCarton")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShipmentOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StyleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPriceCMT")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("UnitPriceDAP")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentOrderId");

                    b.ToTable("ShipmentOrderItems");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.CustomsSettlementItem", b =>
                {
                    b.HasOne("ShoeExportInvoice.Api.Models.Entities.CustomsSettlementPeriod", "SettlementPeriod")
                        .WithMany("Items")
                        .HasForeignKey("SettlementPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SettlementPeriod");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.CustomsSettlementPeriod", b =>
                {
                    b.HasOne("ShoeExportInvoice.Api.Models.Entities.MasterDataFolder", null)
                        .WithMany()
                        .HasForeignKey("ContractFolderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.MasterDataFolder", b =>
                {
                    b.HasOne("ShoeExportInvoice.Api.Models.Entities.MasterDataFolder", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.ProductMaster", b =>
                {
                    b.HasOne("ShoeExportInvoice.Api.Models.Entities.MasterDataFolder", "Folder")
                        .WithMany("Products")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.ShipmentOrder", b =>
                {
                    b.HasOne("ShoeExportInvoice.Api.Models.Entities.MasterDataFolder", null)
                        .WithMany()
                        .HasForeignKey("ContractFolderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.ShipmentOrderItem", b =>
                {
                    b.HasOne("ShoeExportInvoice.Api.Models.Entities.ShipmentOrder", "ShipmentOrder")
                        .WithMany("Items")
                        .HasForeignKey("ShipmentOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipmentOrder");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.CustomsSettlementPeriod", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.MasterDataFolder", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.ShipmentOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
