// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoeExportInvoice.Api.Data;

#nullable disable

namespace ShoeExportInvoice.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910064138_AddCustomsClearanceFields")]
    partial class AddCustomsClearanceFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.ProductMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("HsCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("PairPerCarton")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StyleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPriceCMT")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("UnitPriceCMT_Go")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("UnitPriceDAP")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("UnitPriceDAP_Go")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StyleCode")
                        .IsUnique();

                    b.ToTable("ProductMasters");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.ShipmentOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClearanceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractNo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomsAttachmentFileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomsChannel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomsDeclarationType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CustomsGrossWeight")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("CustomsOffice")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomsPackageQty")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CustomsTotalCmt")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("CustomsTotalDap")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("DeclarationNo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryTerms")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PoSuffix")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationNo");

                    b.HasIndex("InvoiceNo")
                        .IsUnique();

                    b.ToTable("ShipmentOrders");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.ShipmentOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullItemCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShipmentOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StyleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPriceCMT")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("UnitPriceDAP")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentOrderId");

                    b.ToTable("ShipmentOrderItems");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.ShipmentOrderItem", b =>
                {
                    b.HasOne("ShoeExportInvoice.Api.Models.Entities.ShipmentOrder", "ShipmentOrder")
                        .WithMany("Items")
                        .HasForeignKey("ShipmentOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipmentOrder");
                });

            modelBuilder.Entity("ShoeExportInvoice.Api.Models.Entities.ShipmentOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
