import type { ThemeConfig } from 'antd';
import { tokens } from './tokens';

export const enterpriseTheme: ThemeConfig = {
  token: {
    colorPrimary: tokens.colorPrimary,
    colorPrimaryHover: tokens.colorPrimaryHover,
    colorPrimaryActive: tokens.colorPrimaryActive,
    colorBgBase: tokens.surface,
    colorBgLayout: tokens.pageBg,
    colorBgContainer: tokens.surface,
    colorBorder: tokens.border,
    colorBorderSecondary: tokens.borderLight,
    colorText: tokens.textPrimary,
    colorTextHeading: tokens.textPrimary,
    colorTextSecondary: tokens.textSecondary,
    colorTextTertiary: tokens.textMuted,
    colorTextQuaternary: tokens.textDisabled,
    borderRadius: tokens.radiusSm,
    borderRadiusSM: tokens.radiusSm,
    borderRadiusLG: tokens.radiusMd,
    controlHeight: 36,
    controlHeightSM: 30,
    controlHeightLG: 40,
    fontSize: 13,
    fontSizeHeading1: 22,
    fontSizeHeading2: 18,
    fontSizeHeading3: 16,
    fontSizeHeading4: 14,
    fontFamily:
      'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    boxShadow: tokens.shadowCard,
    boxShadowSecondary: tokens.shadowDropdown,
    lineWidth: 1,
    motionDurationFast: '0.1s',
    motionDurationMid: '0.15s',
  },
  components: {
    Table: {
      headerBg: tokens.surfaceSecondary,
      headerColor: tokens.textSecondary,
      borderColor: tokens.border,
      rowHoverBg: tokens.surfaceSecondary,
      headerSplitColor: 'transparent',
      fontSize: 13,
      cellPaddingBlock: 10,
      cellPaddingInline: 12,
      borderRadius: tokens.radiusMd,
    },
    Button: {
      primaryShadow: 'none',
      defaultBorderColor: tokens.borderStrong,
      defaultColor: '#374151',
      defaultBg: '#FFFFFF',
      fontWeight: 500,
      controlHeight: 36,
      borderRadius: tokens.radiusSm,
      colorError: tokens.error,
      colorErrorBg: tokens.surface,
    },
    Input: {
      activeBorderColor: tokens.colorPrimary,
      hoverBorderColor: tokens.borderStrong,
      colorBorder: tokens.border,
      borderRadius: tokens.radiusSm,
      controlHeight: 36,
      fontSize: 13,
    },
    InputNumber: {
      activeBorderColor: tokens.colorPrimary,
      hoverBorderColor: tokens.borderStrong,
      colorBorder: tokens.border,
      borderRadius: tokens.radiusSm,
      controlHeight: 36,
      fontSize: 13,
    },
    Select: {
      colorPrimary: tokens.colorPrimary,
      colorBorder: tokens.border,
      borderRadius: tokens.radiusSm,
      controlHeight: 36,
      fontSize: 13,
    },
    DatePicker: {
      colorPrimary: tokens.colorPrimary,
      colorBorder: tokens.border,
      borderRadius: tokens.radiusSm,
      controlHeight: 36,
      fontSize: 13,
    },
    Card: {
      paddingLG: 20,
      colorBorderSecondary: tokens.border,
      borderRadiusLG: tokens.radiusMd,
      colorBgContainer: tokens.surface,
    },
    Modal: {
      titleFontSize: 16,
      borderRadiusLG: tokens.radiusMd,
      headerBg: tokens.surface,
    },
    Tag: {
      borderRadiusSM: 4,
      defaultBg: tokens.surfaceSecondary,
      defaultColor: tokens.textSecondary,
    },
    Alert: {
      borderRadiusLG: tokens.radiusSm,
    },
    Divider: {
      colorSplit: tokens.border,
      marginLG: 16,
    },
    Tooltip: {
      colorBgSpotlight: '#1F2937',
    },
    Pagination: {
      itemActiveBg: tokens.surface,
      itemBg: 'transparent',
      borderRadius: tokens.radiusSm,
    },
    Dropdown: {
      paddingBlock: 4,
      controlItemBgHover: tokens.surfaceSecondary,
      controlItemBgActive: tokens.colorPrimaryLight,
    },
    Form: {
      labelColor: '#374151',
      labelFontSize: 13,
      verticalLabelPadding: '0 0 5px',
      itemMarginBottom: 16,
    },
    Tabs: {
      cardBg: '#F9FAFB',
      itemSelectedColor: tokens.colorPrimary,
      itemHoverColor: tokens.colorPrimaryHover,
      itemColor: tokens.textSecondary,
      titleFontSize: 13,
    },
    Breadcrumb: {
      fontSize: 12,
      linkColor: tokens.textMuted,
      linkHoverColor: tokens.colorPrimary,
      separatorColor: tokens.borderStrong,
    },
    Drawer: {
      borderRadiusSM: 0,
    },
  },
};

